# Generated by Django 4.2.11 on 2024-05-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsklad',
            name='agreement',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='contractor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='date_receipt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='item_number',
            field=models.CharField(max_length=120, verbose_name='Номенклатурный номер'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='name',
            field=models.CharField(blank=True, max_length=520, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='number_sklad',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='№ склада'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='mainsklad',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Единица измерения'),
        ),
    ]
