# Generated by Django 4.2.11 on 2024-06-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=350, verbose_name='Краткое содержание')),
                ('contractor', models.CharField(max_length=350, verbose_name='Контрагент')),
                ('contract_name', models.CharField(max_length=350, verbose_name='Договор')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('contract_sum', models.DecimalField(decimal_places=3, max_digits=100, verbose_name='Сумма по договору')),
                ('delivery_deadline', models.DateField(null=True, verbose_name='Крайний срок поставки')),
                ('date_receipt', models.DateField(null=True, verbose_name='Дата поступления')),
                ('payment_indicator', models.CharField(max_length=100, verbose_name='Признак оплаты')),
                ('supervising_service', models.CharField(max_length=300, verbose_name='Курирующая служба')),
                ('responsible', models.CharField(max_length=600, verbose_name='Ответственный по договору')),
                ('contract_status', models.CharField(max_length=60, verbose_name='Статус договора')),
                ('receipt_warehouse', models.CharField(max_length=100, verbose_name='Склад поступления')),
                ('responsible_warehouse', models.CharField(max_length=200, verbose_name='Ответственный склада')),
            ],
            options={
                'verbose_name': 'Статус договоров',
            },
        ),
    ]
