# Generated by Django 4.2.11 on 2024-06-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractstatus',
            options={'verbose_name': 'Статус договоров', 'verbose_name_plural': 'Статус договоров'},
        ),
        migrations.AddField(
            model_name='contractstatus',
            name='type_procurement_item',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид предмета'),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='contract_status',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Статус договора'),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='contract_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Сумма по договору'),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='date_receipt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='delivery_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Крайний срок поставки'),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='payment_indicator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Признак оплаты'),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='receipt_warehouse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Склад поступления'),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='responsible_warehouse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответственный склада'),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='short_description',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Краткое содержание'),
        ),
    ]
